Add postgresql adapter for Kysely
vercel/storage pull request #307
Opened 2023-07-25 20:58 UTC by savoiringfaire

The original problem I had which triggered this change was this error when running migrations as documented in https://kysely.dev/docs/migrations

```
VercelPostgresKyselyError [VercelPostgresError]: VercelPostgresError - 'kysely_transactions_not_supported': Transactions are not supported yet.
```

Which we get because we haven't properly signaled to Kysely that we don't support transactions. The Kysely migrator checks `supportsTransactionalDdl` to decide whether to run migrations in a transaction or not, so this adds that.

It also overrides the default migration lock functions from https://github.com/kysely-org/kysely/blob/master/src/dialect/postgres/postgres-adapter.ts to use `pg_advisory_lock` and then unlock with `pg_advisory_unlock` since we can't rely on transactions auto-dropping now.

2023-07-25 21:04 UTC, savoiringfaire commented
Tests on this currently failing due to lack of https://github.com/kysely-org/kysely/issues/456 being officially released.

2023-07-25 21:09 UTC, savoiringfaire commented
Have un-extended the postgresql adapter and implemented the single remaining method in https://github.com/vercel/storage/pull/307/commits/20d17bed8f3e03cb387e42632a629c3e9bc614bd which has got tests passing.

2023-08-12 12:51 UTC, volnei reviewed
Looks great

2023-08-12 18:23 UTC, igalklebanov requested changes

2023-08-12 18:23 UTC, igalklebanov commented on packages/postgres-kysely/src/index.ts
> +
not required. this should be as simple as extending `PostgresAdapter`:

```ts
class VercelPostgresAdapter extends PostgresAdapter {
  get supportsTransactionalDdl(): boolean {
    return false;
  }
}
```

2023-08-12 18:23 UTC, igalklebanov commented on packages/postgres-kysely/src/index.ts
> +
No need, see other comment/s..

```suggestion
```

2023-08-15 12:19 UTC, volnei commented
Can someone explain what I can do have this working?

2023-11-02 16:41 UTC, vvo commented
Hey there, getting back to this. We're investigating how much value our Kysely plugin provides versus a community one: https://github.com/seveibar/kysely-neon. Have any of you tried kysely-neon? We're wondering if we should deprecate our own adapter and delegate it to the community.

As you can tell, we have not been very active in this issue (apologies), which is why we're wondering if it should be owned by the community.

Let us know if https://github.com/seveibar/kysely-neon could work for you, and if not I can re-review this PR.

2023-11-07 16:19 UTC, volnei commented
> Hey there, getting back to this. We're investigating how much value our Kysely plugin provides versus a community one: https://github.com/seveibar/kysely-neon. Have any of you tried kysely-neon? We're wondering if we should deprecate our own adapter and delegate it to the community.
> 
> As you can tell, we have not been very active in this issue (apologies), which is why we're wondering if it should be owned by the community.
> 
> Let us know if https://github.com/seveibar/kysely-neon could work for you, and if not I can re-review this PR.

I agree with you since the kysely neon is an active project and cover all behaviours that vercel kysely do. Can we ensure that? Otherwise I prefer to mantain current with this fixes that I think that is the only problem.

Thanks

2025-01-17 15:17 UTC, vvo commented
Closing very old PRs, if this is a very important PR you can discuss it and reopen it 🙏

2025-01-17 15:17 UTC, closed without merging