switch to __privateGetEdgeConfig
vercel/storage pull request #513
Opened 2023-12-06 20:23 UTC by dferber90

experimental

2023-12-06 20:24 UTC, AndyBitz approved these changes

2023-12-06 20:26 UTC, AAorris approved these changes
lgtm

2023-12-06 21:36 UTC, dvoytenko requested changes

2023-12-06 21:36 UTC, dvoytenko commented on packages/edge-config/src/utils/create-loaders.ts
> +  function __privateGetEdgeConfig(
Can we use a `symbol` instead?

2023-12-08 09:49 UTC, dferber90 commented
Closing as #468 will cache the JSON.parse for now, but we can revisit this later

2023-12-08 09:49 UTC, closed without merging