[edge-config] Make `@opentelemetry/api` optional and add `setTracerProvider` function
vercel/storage pull request #620
Opened 2024-02-22 12:36 UTC by AndyBitz

Fixes #611

By removing the `trace` import, we make the `@opentelemetry/api` fully optional, avoiding errors at build time, when the package does not exist.

Since we have no way of importing the package dynamically, we have to expose the `setTracerProvider` function that consumers of the library can use to set the `trace` themselves whenever they init it.

The `@opentelemetry/api` will continue to be a `peerDependency` that's marked as optional since we make use if its types for the `setTracer` function.

I made this a `minor` as opposed to a `major`, considering we change the API, and it fixes tracing, as it's currently broken, depending on how you see it.

2024-02-24 14:34 UTC, dferber90 requested changes

2024-02-24 14:34 UTC, dferber90 commented on packages/edge-config/src/utils/tracing.ts
> +export function setTracer(tracer: TraceAPI): void {
Seems like the recommended pattern is to use `TracerProvider`?

https://opentelemetry.io/docs/concepts/instrumentation/libraries/#getting-a-tracer

2024-02-24 14:38 UTC, grikomsn approved these changes

2024-02-24 14:52 UTC, dferber90 requested changes

2024-02-24 14:52 UTC, dferber90 commented on .changeset/popular-trees-buy.md
> +Make `@opentelemetry/api` optional and expose a `setTracer` function
```suggestion
Make `@opentelemetry/api` optional and expose a `setTracerProvider` function
```

2024-02-24 14:52 UTC, dferber90 commented on packages/edge-config/README.md
> +The `@vercel/edge-config` package makes use of the OpenTelemetry standard to trace certain functions for observability. In order to enable it, use the function `setTracer` to set the `TraceAPI` that
```suggestion
The `@vercel/edge-config` package makes use of the OpenTelemetry standard to trace certain functions for observability. In order to enable it, use the function `setTracerProvider` to set the `TracerProvider` that should be used by the SDK.
```

2024-02-24 14:52 UTC, dferber90 commented on packages/edge-config/README.md
> +setTracerProvider(trace);
Is this correct?

2024-02-25 20:52 UTC, AndyBitz commented on packages/edge-config/README.md
> +setTracerProvider(trace);
Yes

2024-02-26 10:19 UTC, dferber90 approved these changes

2024-02-26 15:29 UTC, merged